## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [13]:
import pandas as pd
import numpy as np
myfile=pd.read_csv("./data/ccp_current_csv.csv")
myfile.head()


STREET QUADRANT  FROMINTERSECTION              TOINTERSECTION  \
0           13th St       NW        Kennedy St               Longfellow St   
1              S St       NW  North Capitol St                      3rd St   
2  Rhode Island Ave       NE  Brentwood Rd (W)            Brentwood Rd (M)   
3           Mill Rd       NW           27th St                  Cul De Sac   
4  Rhode Island Ave       NE  Brentwood Rd (M)  14th St  Evarts St  Montan   

   NOOFBLOCKS                 WORKDESCRIPTION  YEARBUDGETED  PERCENTCOMPLETED  \
0           1  Pavement Resurface/restoration          2004               100   
1           3                   Regular Cover          1999               100   
2           1  Pavement Resurface/restoration          2004               100   
3           1  Pavement Resurface/restoration          2004               100   
4           2  Pavement Resurface/restoration          2005               100   

      STATUS  MILES      ...             YCOORD   LATITUDE  LONGITUDE  \
0  Completed   0.07      ...       143205.11981  38.956747 -77.029694   
1  Completed   0.33      ...       138468.90256  38.914085 -77.012411   
2  Completed   0.09      ...       139574.10659  38.924041 -76.987221   
3  Completed   0.07      ...       138132.90198  38.911046 -77.054077   
4  Completed   0.16      ...       139657.25318  38.924790 -76.985068   

           PROJECTNOTE                                        PROJECTNAME  \
0                  NaN                                             FedAid   
1                  NaN                                                NaN   
2                  NaN           Fedral Aid Citywide Pavement Restoration   
3  POKA-2003-B-0048-JJ  Citywide Pavement Restoration Contract (Local ...   
4                  NaN                                                NaN   

          PROJECTMGR  PROJECTID        TEAMREP                 EMAIL  \
0    Paul Stephenson       5834        O. Hill                   NaN   
1                NaN       2467            NaN                   NaN   
2  Mohamed Abdullahi       5486   Said Cherifi   said.cherifi@dc.gov   
3    Maduabuchi Udeh       5796  Michael Jelen  Michael.Jelen@dc.gov   
4                NaN       8237            NaN                   NaN   

   CONTACTPHONE  
0  202-671-4591  
1           NaN  
2  202-671-4611  
3  202-671-4542  
4           NaN  

[5 rows x 27 columns]

### 3.1.a  what is its shape and what does that mean?

In [14]:
shape_of_file = myfile.shape
print(shape_of_file)
print(type(shape_of_file))
#shape returns a tuple representing the dimensionality of the DataFrame.
#It means there are 465 rows and 27 columns

(465, 27)
<type 'tuple'>


## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [19]:
print(len(myfile.index))
#there are 465 number of rows
myfile['QUADRANT'].value_counts()
#returns count(number of rows) in each Quadrant

465


NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [51]:
a = np.array([1,2,3,4],dtype=float)
b = np.array([5,6,7,8],dtype=float)
print (a+b) # addition operation
print (np.add(a,b)) # add function

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]


### 3.3.2 subtraction a-b

In [50]:
print (a-b)  #subtraction operation
print(np.subtract(a,b)) # subtract function

[-4. -4. -4. -4.]
[-4. -4. -4. -4.]


### 3.3.3 multiplication a*b

In [51]:
print(a*b) # multiplication operation
print(np.multiply(a,b)) #multiply funcction

[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]


### 3.3.4 divsion a/b

In [52]:
print(a/b) # division operation
print(np.divide(a,b)) #divide function

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


### 3.3.5 modulo  a%b

In [53]:
print(a%b) #modulo operation
print(np.mod(a,b)) # mod function

[1. 2. 3. 4.]
[1. 2. 3. 4.]


### 3.3.6 power  a^b

In [54]:
print(a**b) #power operation
print(np.power(a,b)) #power function

[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


### 3.3.7 Other functions


#### Absolute function
This mathematical function helps user to calculate absolute value of each element.

In [80]:
np.absolute(a)

array([1., 2., 3., 4.])

#### Trigonometric functions

In [71]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))



[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


#### Exponents and logarithms

In [74]:
print("b    =", b)
print("e^b  =", np.exp(b))
print("2^b   =", np.exp2(b))
print("3^b  =", np.power(3, b))
print("ln(b)    =", np.log(b))
print("log2(b)  =", np.log2(b))
print("log10(b) =", np.log10(b))

('b    =', array([5., 6., 7., 8.]))
('e^b  =', array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704]))
('2^b   =', array([ 32.,  64., 128., 256.]))
('3^b  =', array([ 243.,  729., 2187., 6561.]))
('ln(b)    =', array([1.60943791, 1.79175947, 1.94591015, 2.07944154]))
('log2(b)  =', array([2.32192809, 2.5849625 , 2.80735492, 3.        ]))
('log10(b) =', array([0.69897   , 0.77815125, 0.84509804, 0.90308999]))


#### Aggregate functions

##### Reduce function
A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [75]:
np.add.reduce(b)

26.0

In [76]:
np.multiply.reduce(b)

1680.0

#####  Accumulate Function
This function is used to Accumulate the result of applying the operator to all elements.

In [77]:
np.add.accumulate(a)

array([ 1.,  3.,  6., 10.])

#### Outer products
This allows you, in one line, to do things like create a multiplication table.

In [79]:
np.multiply.outer(a,b)

array([[ 5.,  6.,  7.,  8.],
       [10., 12., 14., 16.],
       [15., 18., 21., 24.],
       [20., 24., 28., 32.]])

#### Scalar Product / Dot Product
This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication. For 1-D arrays, it is the inner product of the vectors. For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b.

In [52]:
dot =np.dot(a,b)
dot

70.0

In [53]:
a_modulus = np.sqrt((a*a).sum())
b_modulus = np.sqrt((b*b).sum())
cos_angle = dot / a_modulus / a_modulus # returns cosine of angle between a and b
cos_angle

2.3333333333333335

#### Pi

In [54]:
cos_angle * 360 / 2 / np.pi # returns angle in degrees

133.69015219719208

#### Cross product
This function returns the cross product of two arrays.

In [55]:
x = np.array([0,0,1])
y = np.array([0,1,0])
np.cross(x,y)

array([-1,  0,  0])

In [66]:
np.cross(y,x)

array([1, 0, 0])

## Boolean Indexing of Array

In [5]:
A = np.array([2,6,1,8,4,1,0])
print(A == 1)
print(A > 5)

[False False  True False False  True False]
[False  True False  True False False False]


In [6]:
#also works on higher dimensions

B = np.array([[4,56,89,65],
              [99,88,36,12],
              [55,92,7,18]])
print(B>=42)

[[False  True  True  True]
 [ True  True False False]
 [ True  True False False]]


### Fancy Indexing
If arrays are indexed by using boolean or integer arrays (masks). The result will be a copy and not a view.

In [20]:
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])
R = C[A<=5]
print(R)
## Indexing with an Integer Array
print(C[[0, 2, 3, 1, 4, 1]])

[123 190 100]
[123 190  99 188  77 188]


### Non zero
an ndarray a both numpy.nonzero(a) and a.nonzero() return the indices of the elements of a that are non-zero. The indices are returned as a tuple of arrays, one for each dimension of 'a'. The corresponding non-zero values can be obtained 

In [21]:
nz = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])
print(nz.nonzero())

#If you want to group the indices by element, you can use transpose :transpose(nonzero(nz))
np.transpose(nz.nonzero())

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 4, 0, 3, 0, 3], dtype=int64))


array([[0, 1],
       [0, 2],
       [0, 4],
       [1, 0],
       [1, 3],
       [2, 0],
       [2, 3]], dtype=int64)

The function 'nonzero' can be used to obtain the indices of an array, where a condition is True. In the following script, we create the Boolean array B >= 42

In [22]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
print(B >= 42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


## Homework 3.4
Find your own data and load it into a dataframe

In [34]:
# the dataset was downloaded from https://www.kaggle.com/davidrgp/pokedex

poke_data = pd.read_csv("./data/pokemon.csv")
poke_data.head()

id     pokemon  species_id  height  weight  base_experience type_1  type_2  \
0   1   bulbasaur           1       7      69               64  grass  poison   
1   2     ivysaur           2      10     130              142  grass  poison   
2   3    venusaur           3      20    1000              236  grass  poison   
3   4  charmander           4       6      85               62   fire     NaN   
4   5  charmeleon           5      11     190              142   fire     NaN   

   attack  defense    ...      color_2  color_f  egg_group_1  egg_group_2  \
0      49       49    ...      #A040A0  #81A763      monster        plant   
1      62       63    ...      #A040A0  #81A763      monster        plant   
2      82       83    ...      #A040A0  #81A763      monster        plant   
3      52       43    ...          NaN      NaN      monster       dragon   
4      64       58    ...          NaN      NaN      monster       dragon   

  url_image generation_id evolves_from_species_id evolution_chain_id shape_id  \
0     1.png           1.0                     NaN                1.0      8.0   
1     2.png           1.0                     1.0                1.0      8.0   
2     3.png           1.0                     2.0                1.0      8.0   
3     4.png           1.0                     NaN                2.0      6.0   
4     5.png           1.0                     4.0                2.0      6.0   

       shape  
0  quadruped  
1  quadruped  
2  quadruped  
3    upright  
4    upright  

[5 rows x 28 columns]

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [35]:
# check the data frame info
print(poke_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 28 columns):
id                         811 non-null int64
pokemon                    811 non-null object
species_id                 811 non-null int64
height                     811 non-null int64
weight                     811 non-null int64
base_experience            811 non-null int64
type_1                     811 non-null object
type_2                     414 non-null object
attack                     811 non-null int64
defense                    811 non-null int64
hp                         811 non-null int64
special_attack             811 non-null int64
special_defense            811 non-null int64
speed                      811 non-null int64
ability_1                  811 non-null object
ability_2                  402 non-null object
ability_hidden             654 non-null object
color_1                    811 non-null object
color_2                    414 non-null object
color_f      

value_counts() - Returns object containing counts of unique values.

In [36]:
poke_data['type_1'].value_counts()

#value_counts will return NumPy array with unique items and the frequency of it.

water       114
normal       98
grass        70
bug          69
psychic      57
fire         53
electric     50
rock         44
dragon       32
ground       32
ghost        32
dark         31
poison       28
fighting     27
steel        27
ice          25
fairy        18
flying        4
Name: type_1, dtype: int64

In [37]:
len(poke_data)
# returns the number of rows

811

### Simple Aggregation in Pandas
- count()	-Total number of items
- first(), last()	-First and last item
- mean(), median()	-Mean and median 
- min(), max()	-Minimum and maximum
- std(), var()-	Standard deviation and variance
- mad()	-Mean absolute deviation
- prod()-	Product of all items
- sum()	-Sum of all items

In [38]:
poke_data.count()
# returns number of non-NA elements in a Series

id                         811
pokemon                    811
species_id                 811
height                     811
weight                     811
base_experience            811
type_1                     811
type_2                     414
attack                     811
defense                    811
hp                         811
special_attack             811
special_defense            811
speed                      811
ability_1                  811
ability_2                  402
ability_hidden             654
color_1                    811
color_2                    414
color_f                    414
egg_group_1                811
egg_group_2                216
url_image                  718
generation_id              721
evolves_from_species_id    355
evolution_chain_id         721
shape_id                   721
shape                      721
dtype: int64

In [45]:
count_of_nan = len(poke_data) - poke_data.count()
print(count_of_nan)
#returns the number of missing elements in each coloumn

id                           0
pokemon                      0
species_id                   0
height                       0
weight                       0
base_experience              0
type_1                       0
type_2                     397
attack                       0
defense                      0
hp                           0
special_attack               0
special_defense              0
speed                        0
ability_1                    0
ability_2                  409
ability_hidden             157
color_1                      0
color_2                    397
color_f                    397
egg_group_1                  0
egg_group_2                595
url_image                   93
generation_id               90
evolves_from_species_id    456
evolution_chain_id          90
shape_id                    90
shape                       90
dtype: int64


In [40]:
# returns the heaviest pokemon

heavy_poke = poke_data['weight'].max()

poke_data.loc[poke_data['weight'] == heavy_poke]


id         pokemon  species_id  height  weight  base_experience  \
798  10078  groudon-primal         383     500    9997              347   

     type_1 type_2  attack  defense  ...   color_2  color_f  egg_group_1  \
798  ground   fire     180      160  ...   #F08030  #E3B05A      no-eggs   

     egg_group_2 url_image generation_id evolves_from_species_id  \
798          NaN       NaN           NaN                     NaN   

    evolution_chain_id shape_id shape  
798                NaN      NaN   NaN  

[1 rows x 28 columns]

In [41]:
# returns the tallest pokemon

tall_poke = poke_data['height'].max()

poke_data.loc[poke_data['height'] == tall_poke]

id        pokemon  species_id  height  weight  base_experience  \
799  10079  rayquaza-mega         384    1080    3920              351   

     type_1  type_2  attack  defense  ...   color_2  color_f  egg_group_1  \
799  dragon  flying     180      100  ...   #A890F0  #7D4DF6      no-eggs   

     egg_group_2 url_image generation_id evolves_from_species_id  \
799          NaN       NaN           NaN                     NaN   

    evolution_chain_id shape_id shape  
799                NaN      NaN   NaN  

[1 rows x 28 columns]

In [42]:
# to find the mean and median of the height
poke_data['height'].mean()

20.384710234278668

In [43]:
# returns the pokemons whose height is same as the median of the heights
poke_data.loc[poke_data['height'] == poke_data['height'].median()]

id                pokemon  species_id  height  weight  \
1        2                ivysaur           2      10     130   
7        8              wartortle           8      10     225   
14      15               beedrill          15      10     295   
27      28              sandslash          28      10     295   
39      40             wigglytuff          40      10     120   
46      47               parasect          47      10     295   
47      48                venonat          48      10     300   
52      53                persian          53      10     320   
56      57               primeape          57      10     320   
60      61              poliwhirl          61      10     200   
69      70             weepinbell          70      10      64   
74      75               graveler          75      10    1050   
76      77                 ponyta          77      10     300   
81      82               magneton          82      10     600   
95      96                drowzee          96      10     324   
104    105                marowak         105      10     450   
110    111                rhyhorn         111      10    1150   
113    114                tangela         114      10     350   
133    134               vaporeon         134      10     290   
138    139                omastar         139      10     350   
164    165                 ledyba         165      10     108   
196    197                umbreon         197      10     270   
261    262              mightyena         262      10     370   
266    267              beautifly         267      10     284   
273    274                nuzleaf         274      10     280   
293    294                loudred         294      10     405   
295    296               makuhita         296      10     864   
298    299               nosepass         299      10     970   
336    337               lunatone         337      10    1680   
344    345                 lileep         345      10     238   
351    352                kecleon         352      10     220   
368    369              relicanth         369      10     234   
399    400                bibarel         400      10     315   
401    402             kricketune         402      10     255   
431    432                purugly         432      10     438   
434    435               skuntank         435      10     380   
441    442              spiritomb         442      10    1080   
457    458                mantyke         458      10     650   
458    459                 snover         459      10     505   
469    470                leafeon         470      10     255   
498    499                pignite         499      10     555   
513    514               simisear         514      10     280   
515    516               simipour         516      10     290   
549    550   basculin-red-striped         550      10     180   
551    552               krokorok         552      10     334   
555    556               maractus         556      10     280   
578    579              reuniclus         579      10     201   
588    589             escavalier         589      10     330   
597    598             ferrothorn         598      10    1100   
605    606               beheeyem         606      10     345   
608    609             chandelure         609      10     343   
610    611                fraxure         611      10     360   
621    622                 golett         622      10     920   
653    654                braixen         654      10     145   
659    660              diggersby         660      10     424   
694    695              heliolisk         695      10     210   
699    700                sylveon         700      10     235   
711    712               bergmite         712      10     995   
736  10016  basculin-blue-striped         550      10     180   
772  10052            mawile-mega         303      10     235   

     base_experience    type_1    type_2  

### GroupBy: Split, Apply, Combine

In [44]:
#Groupby on type_1 and sort by height in decending order.

c = poke_data.groupby('type_1').sum()
c = c.sort_values(['height'], ascending=False)
c

id  species_id  height  weight  base_experience  attack  \
type_1                                                                  
water     122532       34847    3115   68812            16536    8467   
dragon     92054       15180    2028   41501             7182    3588   
steel      60362       11957    1697   56062             5025    2503   
normal     79826       31279    1439   42316            14197    7200   
psychic   118388       21706    1378   23852            10376    4073   
grass      63096       24141     894   29161            10148    5125   
ground     30472       11401     875   42095             4751    3064   
fire       76114       17376     865   36841             8628    4478   
bug        81918       23080     746   21428             8577    4897   
rock       46337       17280     699   44929             6458    4086   
electric  153131       16144     639   15521             7670    3370   
ice        29892       10516     491   27260             3758    1816   
ghost     100648       15568     413   21032             4688    2361   
dark       43583       14302     402   13753             4482    2740   
poison      7050        7050     340   10254             3519    2091   
fighting   29181        9824     318   14621             3644    2613   
fairy      17703        8312     144    4246             2666    1111   
flying     12089        2711      49    2190              758     315   

          defense    hp  special_attack  special_defense  speed  \
type_1                                                            
water        8305  8211            8529             8023   7556   
dragon       2764  2666            3099             2843   2657   
steel        3412  1761            1823             2177   1492   
normal       5865  7573            5470             6245   7012   
psychic      3858  4026            5609             4918   4645   
grass        4956  4709            5425             4930   4335   
ground       2715  2361            1807             2008   2045   
fire         3594  3705            4697             3825   3941   
bug          4880  3925            3717             4471   4256   
rock         4435  2876            2787             3321   2460   
electric     3157  2841            4261             3543   4258   
ice          1784  1798            1931             1901   1593   
ghost        2598  2062            2539             2447   2059   
dark         2177  2071            2314             2155   2361   
poison       1927  1883            1692             1803   1780   
fighting     1780  1886            1434             1747   1784   
fairy        1184  1334            1460             1568    918   
flying        265   283             377              290    410   

          generation_id  evolves_from_species_id  evolution_chain_id  shape_id  
type_1                                                                          
water             303.0                  15479.0             15940.0     705.0  
dragon             95.0                   4888.0              5944.0     142.0  
steel              87.0                   4447.0              5075.0     165.0  
normal            283.0                  11679.0             13898.0     734.0  
psychic           162.0                   7562.0              8717.0     393.0  
grass             223.0                  11292.0             11135.0     506.0  
ground             93.0                   4545.0              4925.0     231.0  
fire              154.0                   8184.0              7864.0     332.0  
bug               208.0                  11050.0             10802.0     615.0  
rock              143.0                   6864.0              8001.0     315.0  
electric          114.0                   4853.0              5779.0     228.0  
ice                82.0                   4751.0              4573.0     169.0  
ghost              90.0                   5069.0              5095.0     105.0

As with the GroupBy object, no computation is done until we call some aggregate on the object:

In [25]:
poke_data.groupby('type_2')['weight']

In [24]:
poke_data.groupby('type_2')['weight'].median()

type_2
bug          125.0
dark         694.5
dragon       835.0
electric     131.5
fairy        115.0
fighting     520.0
fire         315.5
flying       280.0
ghost        298.0
grass        125.0
ground       620.0
ice         1340.0
normal       172.5
poison       127.5
psychic      600.0
rock         705.0
steel        650.0
water        332.5
Name: weight, dtype: float64

### Iteration over groups
The GroupBy object supports direct iteration over the groups, returning each group as a Series or DataFrame

In [26]:
for (method, group) in poke_data.groupby('type_2'):
    print("{0:30s} shape={1}".format(method, group.shape))

bug                            shape=(3, 28)
dark                           shape=(20, 28)
dragon                         shape=(18, 28)
electric                       shape=(6, 28)
fairy                          shape=(23, 28)
fighting                       shape=(26, 28)
fire                           shape=(12, 28)
flying                         shape=(97, 28)
ghost                          shape=(14, 28)
grass                          shape=(25, 28)
ground                         shape=(35, 28)
ice                            shape=(14, 28)
normal                         shape=(4, 28)
poison                         shape=(34, 28)
psychic                        shape=(33, 28)
rock                           shape=(14, 28)
steel                          shape=(22, 28)
water                          shape=(14, 28)


### Dispatch methods
We can use the describe() method of DataFrames to perform a set of aggregations that describe each group in the data.

In [28]:
poke_data.groupby('type_2')['weight'].describe().unstack()

       type_2  
count  bug            3.000000
       dark          20.000000
       dragon        18.000000
       electric       6.000000
       fairy         23.000000
       fighting      26.000000
       fire          12.000000
       flying        97.000000
       ghost         14.000000
       grass         25.000000
       ground        35.000000
       ice           14.000000
       normal         4.000000
       poison        34.000000
       psychic       33.000000
       rock          14.000000
       steel         22.000000
       water         14.000000
mean   bug          309.000000
       dark        1118.650000
       dragon      1996.277778
       electric     675.666667
       fairy        169.956522
       fighting     727.730769
       fire        1295.416667
       flying       479.845361
       ghost        651.142857
       grass        218.920000
       ground      1258.428571
       ice         1522.142857
                      ...     
75%    fire         468

### Aggregation
aggregate() can take a string, a function, or a list thereof, and compute all the aggregates at once.

In [31]:
poke_data.groupby('type_2').aggregate([min, np.median, max])

id               species_id             height              weight  \
          min median    max        min median  max    min median   max    min   
type_2                                                                          
bug       347  348.0    451        347  348.0  451      7    8.0    15    120   
dark      248  447.0  10086        130  388.0  720      4   13.0   650    152   
dragon    230  663.0  10065          6  487.0  715      5   18.0   190     80   
electric  170  595.5    644        170  595.5  644      1    7.5    29      6   
fairy      39  439.0  10075         39  303.0  719      2    7.0   150      6   
fighting   62  559.5  10088         62  464.5  652      6   14.5   160     65   
fire      228  622.5  10078        228  550.5  643      3   10.5   500      3   
flying      6  373.0  10089          6  291.0  717      2   12.0  1080      3   
ghost     292  622.5  10066        292  607.5  720      3   11.0    50      3   
grass      46  585.0  10032         46  542.0  711      3    7.0    19      3   
ground     31  323.0  10087         31  290.0  718      4   13.0  1050     19   
ice        87  553.5  10060         87  460.5  699      3   19.5    36      3   
normal    667  681.0    695        667  681.0  695      5    8.0    15     60   
poison      1   92.5  10090          1   72.5  591      2   10.0   140      1   
psychic    79  375.0  10076         79  344.0  687      3   13.0   250     11   
rock      111  305.5    565        111  305.5  565      3    9.5    24     50   
steel      81  507.5  10059         81  455.0  649      3   12.0    20     60   
water     138  364.5  10009        138  364.5  721      3    9.0    17      3   

          ...  generation_id evolves_from_species_id                \
          ...            max                     min median    max   
type_2    ...                                                        
bug       ...            4.0                   347.0  347.0  347.0   
dark      ...            6.0                   247.0  387.5  674.0   
dragon    ...            6.0                   117.0  633.5  714.0   
electric  ...            5.0                   170.0  382.5  595.0   
fairy     ...            6.0                    39.0  280.5  546.0   
fighting  ...            6.0                    61.0  390.5  651.0   
fire      ...            5.0                   228.0  607.5  636.0   
flying    ...            6.0                     5.0  276.0  665.0   
ghost     ...            6.0                   290.0  607.0  680.0   
grass     ...            6.0                    46.0  476.0  710.0   
ground    ...            6.0                    30.0  258.5  659.0   
ice       ...            6.0                    86.0  215.0  698.0   
normal    ...            6.0                   667.0  680.5  694.0   
poison    ...            5.0                     1.0   72.0  590.0   
psychic   ...            6.0                    79.0  325.0  686.0   
rock      ...            5.0                   111.0  304.0  564.0   
steel     ...            5.0                    81.0  402.0  624.0   
water     ...            6.0                   138.0  363.5  688.0   

         evolution_chain_id               shape_id               
                        min median    max      min median   max  
type_2                                                           
bug                   177.0  177.0  234.0      6.0   14.0  14.0  
dark                  126.0  223.0  346.0      3.0    8.0  14.0  
dragon                 54.0  323.0  367.0      5.0    8.0  13.0  
electric               86.0  303.0  331.0      3.0    4.5  14.0  
fairy                  16.0  140.0  371.0      1.0   12.0  12.0  
fighting               26.0  235.0  337.0      6.0    6.0  12.0  
fire                  118.0  308.0  330.0      4.0    8.0  14.0  
flying                  2.0  135.0  369.0      2.0    9.0  13.0  
ghost                 144.0  308.5  372.0      1.0    7.5  12.0  
grass                  19.0  244.5  365.0     

Another useful pattern is to pass a dictionary mapping column names to operations to be applied on that column.

In [35]:
#returns the type of pokemon with minimum height and maximum weight
poke_data.groupby('type_2').aggregate({'height': 'min',
                             'weight': 'max'})

weight  height
type_2                  
bug          682       7
dark        4900       4
dragon      7500       5
electric    3450       1
fairy        545       2
fighting    2600       6
fire        9997       3
flying      3920       2
ghost       3300       3
grass        925       3
ground      7400       4
ice         3250       3
normal       815       5
poison      2005       2
psychic     9429       3
rock        3600       3
steel       4300       3
water       1950       3

### Filtering
A filtering operation allows you to drop data based on the group properties.

In [44]:
#returns only pokemons whose standard deviation of its height is greater than 150.
def func(x):
    return x['height'].std() > 150
display(poke_data.groupby('type_2').filter(func))

id         pokemon  species_id  height  weight  base_experience  \
30      31       nidoqueen          31      13     600              227   
33      34        nidoking          34      14     620              227   
73      74         geodude          74       4     200               60   
74      75        graveler          75      10    1050              137   
75      76           golem          76      14    3000              223   
94      95            onix          95      88    2100               77   
193    194          wooper         194       4      85               42   
194    195        quagsire         195      14     750              151   
207    208         steelix         208      92    4000              179   
219    220          swinub         220       4      65               50   
220    221       piloswine         221      11     558              158   
245    246        larvitar         246       6     720               60   
246    247         pupitar         247      12    1520              144   
258    259       marshtomp         259       7     280              142   
259    260        swampert         260      15     819              241   
289    290         nincada         290       5      55               53   
321    322           numel         322       7     240               61   
322    323        camerupt         323      19    2200              161   
338    339        barboach         339       4      19               58   
339    340        whiscash         340       9     236              164   
388    389        torterra         389      22    3100              236   
422    423       gastrodon         423       9     299              166   
442    443           gible         443       7     205               60   
443    444          gabite         444      14     560              144   
444    445        garchomp         445      19     950              270   
472    473       mamoswine         473      25    2910              239   
535    536       palpitoad         536       8     170              134   
536    537      seismitoad         537      15     620              229   
659    660       diggersby         660      10     424              148   
717    718         zygarde         718      50    3050              270   
724  10004  wormadam-sandy         413       5      65              148   
778  10058   garchomp-mega         445      19     950              315   
784  10064   swampert-mega         260     190    1020              286   
792  10072    steelix-mega         208    1050    7400              214   
807  10087   camerupt-mega         323     250    3205              196   

     type_1  type_2  attack  defense    ...      color_2  color_f  \
30   poison  ground      92       87    ...      #E0C068  #AF5F92   
33   poison  ground     102       77    ...      #E0C068  #AF5F92   
73     rock  ground      80      100    ...      #E0C068  #C1A743   
74     rock  ground      95      115    ...      #E0C068  #C1A743   
75     rock  ground     120      130    ...      #E0C068  #C1A743   
94     rock  ground      45      160    ...      #E0C068  #C1A743   
193   water  ground      45       45    ...      #E0C068  #859BCF   
194   water  ground      85       85    ...      #E0C068  #859BCF   
207   steel  ground      85      200    ...      #E0C068  #C1B9B6   
219     ice  ground      50       40    ...      #E0C068  #A9D2BC   
220     ice  ground     100       80    ...      #E0C068  #A9D2BC   
245    rock  ground      64       50    ...      #E0C068  #C1A743   
246    rock  ground      84       70    ...      #E0C068  #C1A743   
258   water  ground      85       70    ...      #E0C068  #859BCF   
259   water  ground     110       90    ...      #E0C068  #859BCF   
289     bug  ground      45       90    ...      #E0C068  #B5B931   
321    fire  ground      60       40    ...      #E0C068  #EC8F3D   
322    fire  ground     100       70    ...      #E0C068  #EC8F3D

## Handling Missing Data

In [58]:
# dropping two columns which has more missing elements
poke_data.drop(['evolves_from_species_id','egg_group_2'],axis=1,inplace=True)

poke_data.head()

id     pokemon  species_id  height  weight  base_experience type_1  type_2  \
0   1   bulbasaur           1       7      69               64  grass  poison   
1   2     ivysaur           2      10     130              142  grass  poison   
2   3    venusaur           3      20    1000              236  grass  poison   
3   4  charmander           4       6      85               62   fire     NaN   
4   5  charmeleon           5      11     190              142   fire     NaN   

   attack  defense    ...      ability_hidden  color_1  color_2  color_f  \
0      49       49    ...         chlorophyll  #78C850  #A040A0  #81A763   
1      62       63    ...         chlorophyll  #78C850  #A040A0  #81A763   
2      82       83    ...         chlorophyll  #78C850  #A040A0  #81A763   
3      52       43    ...         solar-power  #F08030      NaN      NaN   
4      64       58    ...         solar-power  #F08030      NaN      NaN   

  egg_group_1 url_image generation_id evolution_chain_id shape_id      shape  
0     monster     1.png           1.0                1.0      8.0  quadruped  
1     monster     2.png           1.0                1.0      8.0  quadruped  
2     monster     3.png           1.0                1.0      8.0  quadruped  
3     monster     4.png           1.0                2.0      6.0    upright  
4     monster     5.png           1.0                2.0      6.0    upright  

[5 rows x 26 columns]

In [59]:
#filling missing values in type_2 and ability_2
values = {'type_2': 'No Type', 'ability_2' : 'Unknown'}
poke_data.fillna(value= values,inplace=True)
poke_data.head()

id     pokemon  species_id  height  weight  base_experience type_1  \
0   1   bulbasaur           1       7      69               64  grass   
1   2     ivysaur           2      10     130              142  grass   
2   3    venusaur           3      20    1000              236  grass   
3   4  charmander           4       6      85               62   fire   
4   5  charmeleon           5      11     190              142   fire   

    type_2  attack  defense    ...      ability_hidden  color_1  color_2  \
0   poison      49       49    ...         chlorophyll  #78C850  #A040A0   
1   poison      62       63    ...         chlorophyll  #78C850  #A040A0   
2   poison      82       83    ...         chlorophyll  #78C850  #A040A0   
3  No Type      52       43    ...         solar-power  #F08030      NaN   
4  No Type      64       58    ...         solar-power  #F08030      NaN   

   color_f egg_group_1 url_image generation_id evolution_chain_id shape_id  \
0  #81A763     monster     1.png           1.0                1.0      8.0   
1  #81A763     monster     2.png           1.0                1.0      8.0   
2  #81A763     monster     3.png           1.0                1.0      8.0   
3      NaN     monster     4.png           1.0                2.0      6.0   
4      NaN     monster     5.png           1.0                2.0      6.0   

       shape  
0  quadruped  
1  quadruped  
2  quadruped  
3    upright  
4    upright  

[5 rows x 26 columns]

## Reference

[1] https://www.kaggle.com/davidrgp/pokedex
[2] https://pandas.pydata.org/
[3] https://www.python-course.eu/matrix_arithmetic.php